name: Update publications

on:
  schedule:
    - cron: "0 8 * * 1"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-publications:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Python packages
        run: |
          pip install requests

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Update publications
        run: |
          python .github/workflows/update_publications.py

      - name: Render website
        run: |
          quarto render

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/publications.json docs
          git commit -m "Automatic publication update" || exit 0
          git push